sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install -r requirements-dev.txt --download-cache $HOME/.cache/pip
  - pip install -r requirements.txt --download-cache $HOME/.cache/pip
  - pip install -e . --download-cache $HOME/.cache/pip
  - pip install coveralls --download-cache $HOME/.cache/pip
script:
  - flake8
  - py.test
services:
  - elasticsearch
after_success:
  - coveralls
