language: python
python:
  - "2.7"
matrix:
  include:
    - python: "pypy"
      env: PYPY_VERSION="5.0.0" NO_COVERAGE=1
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.hypothesis
env:
  global:
    - HYPOTHESIS_DATABASE_FILE=$HOME/.hypothesis/examples.db
services:
  - elasticsearch

before_install:
  - mkdir -p $HOME/.hypothesis
  # If necessary, set up an appropriate version of pypy.
  - if [ ! -z "$PYPY_VERSION" ]; then source setup-pypy-travis.sh; fi
  - if [ ! -z "$PYPY_VERSION" ]; then python --version 2>&1 | fgrep "PyPy $PYPY_VERSION"; fi

install:
  # Upgrade pip to get wheel caching
  - pip install --upgrade pip>=8.1.0
  # Bug in django-appregister requires that Django is installed first
  - pip install "Django >=1.8,<1.9"
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_OPT="--cov mc2"; else COVERAGE_OPT=""; fi
  - py.test $COVERAGE_OPT

after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: EPm458KmHwAsUgKzS+MUtPqWySdK8bLVyv4ndI5/jEYislvqYJCS4kDOUU15etyY3wvf4pppcAGuAIDkNKdKZl+YWLtvmfRlH8TPpUjL+ysphqlmnMSt/SznSZDyT+PWW0PknmDANxIbuwkI/ZeP140iEnYOFIc5g0OYmV9H9/BqSJ0HsoKHJ2vV7/Z+c1GOkKY7ncqBmwc1Ym2I9/UBVRlhOYIqnqwZRRZLoNteLLbISAsVyVg4xDgaFDETn0roahm7lwZX7WgY2YTGoJiO/wEARrcbAg+AVq5qVBrgxAP2X2Uk9+yx19OD9SdG2KIVs9mXVePtXbK2afNK0G2Pi+SoaXsiKOMUjSqrB4EWt63uJgF7DY/VQFZMxOM7j2mp7dN2S1LwQhYGfjY1kWIHp7Uo9c9gGxZfxCGubS6zTCyNmxXVqJrwR7zxKm1Zlz7yDKyAnikjIaRqaM++4WVG/vFgKqbPTNodX0ypfN+ABIi7Ju1NRh13HywzO+2CxWv+ltv2XBazIKaJcxDUuiGP61nVWyhm+eCSkeo+l8e7dmx4/PAQW8L9OG4dw4/aPzPqKzW7FwbzanKPxR41Hz5dOrbE29+Us6gEhEXVtg78iaaApMXwPLO9s0QGDA7kaQZ23QIVlvGhFjFt6DL1jFHnmxf9UVJ1gKow3lUgN5Cl83I=
  on:
    tags: true
    all_branches: true
