language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -r requirements.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install coveralls --use-wheel
script:
  - ./run_tests.sh
services:
  - elasticsearch
after_success:
  - coveralls
